name: generate-contribution-snake-animation

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: shared-execution-lock
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7.0.1
      - uses: luiz1361/snk@a041d6c27ba561a39f5be9c26a784812765e434b # ratchet:luiz1361/snk@v3.5.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            github-snake.svg
            github-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          mkdir -p contribution-snake-animation
          mv github-snake.svg contribution-snake-animation/light.svg
          mv github-snake-dark.svg contribution-snake-animation/dark.svg
          git add -A .
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "ci: generate-contribution-snake-animation"
            git push
          fi
